# Generated by Django 5.2.5 on 2025-10-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_touristspotimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
